### ISSUE TITLE
how to use pod install

### ISSUE THREAD

**Issue by My-Old-Driver** [horizontalsystems/bitcoin-kit-ios#105]
pod 'WalletKit'
`[!] Unable to find a specification for WalletKit`

**Comment by ealymbaev** [comment]
Our library is not released to Cocoapods yet. But you can use it by configuring your podfile as follows:

`pod 'WalletKit', git: 'https://github.com/horizontalsystems/wallet-kit-ios.git', branch: 'dev'`

**Comment by TACGalang** [comment]
how to install it? 
[!] Unable to find a specification for 'bitcoin-kit-ios'.
