### ISSUE TITLE
[!] Unable to find a pod with name, author, summary, or description matching `HSCryptoKit`

### ISSUE THREAD

**Issue by fanxiaofan** [horizontalsystems/bitcoin-kit-ios#107]
[!] Unable to find a pod with name, author, summary, or description matching `HSCryptoKit`.
Pod cannot search HSCryptoKit!

**Comment by ealymbaev** [comment]
It seems like your local repo is not updated, please try using `pod repo update`.
`HSCryptoKit` pod is released already: https://cocoapods.org/pods/HSCryptoKit
