### ISSUE TITLE
use random string for local DB name

### ISSUE THREAD

**Issue by ealymbaev** [horizontalsystems/bitcoin-kit-ios#217]
Now all 12 mnemonic words are used in creating Sha256 hash that is used in database name.
It is not quite secure, so only first and last word should be used for hashing.

**Comment by esengulov** [comment]
> Now all 12 mnemonic words are used in creating Sha256 hash that is used in database name.
> It is not quite secure, so only first and last word should be used for hashing.

instead better to use random string for dB
