### ISSUE TITLE
Long syncing issues

### ISSUE THREAD

**Issue by CryoCodex** [horizontalsystems/bitcoin-kit-ios#246]
Hi! I was wondering if it is okay that the syncing progress takes long now? it used to be way shorter 2 days ago, did something change? also, it seems when you're trying to send a transaction now, it keeps failing due to it is always getting blocks over and over, until it stabilizes for a little bit and you can send it then it goes back to fetching blocks, which is also something that wasn't happening that constantly 2 days ago, just little observations I've noticed since the last time I've been using the library, I've been pretty much studying the library by looking through your demo project but it also takes longer to sync now and to send transactions it's a little unstable since it always keeps fetching blocks sometimes on your demo project too

**Comment by esengulov** [comment]
> Hi! I was wondering if it is okay that the syncing progress takes long now? it used to be way shorter 2 days ago, did something change? also, it seems when you're trying to send a transaction now, it keeps failing due to it is always getting blocks over and over, until it stabilizes for a little bit and you can send it then it goes back to fetching blocks, which is also something that wasn't happening that constantly 2 days ago, just little observations I've noticed since the last time I've been using the library, I've been pretty much studying the library by looking through your demo project but it also takes longer to sync now and to send transactions it's a little unstable since it always keeps fetching blocks sometimes on your demo project too

Hi there, thanks for heads up. The wallet sync logic as well as the speed of wallet restore is work in progress and being improved. I have just added another issue (a quick fix) that should address the speed of restore process. Aiming to get this included in the next update, coming hopefully next week.

https://github.com/horizontalsystems/bitcoin-kit-ios/issues/248

**Comment by CryoCodex** [comment]
Hey! sorry for the late reply, but yeah alright! thanks so much for the response

**Comment by ealymbaev** [comment]
Glad that improvement helped you.
I have also created another issue #253 related to send issues.
Closing this issue.
