### ISSUE TITLE
API Usage, low level access

### ISSUE THREAD

**Issue by r00li** [horizontalsystems/bitcoin-kit-ios#272]
Hi!
I am looking into this library for a project that I am working on and I have two questions.

First of all... I was looking at the example and I noticed that the library is making calls to http://btc-testnet.horizontalsystems.xyz/apg. Can somebody tell me why and if it is possible to easily remove these calls? If not at least give me some details on what is returned so we can maybe replace it with our own backend.

The second one is more complicated. Our client is developing a hardware wallet and for us to successfully implement support for that we need to get access to the low level transaction data that we can then send to the device for signature. My question is - how hard would it be to modify this library so it could be initialized without mnemonics/seed (so in "read only" mode) and modify it to get access to the raw transaction data so that the hardware device can provide the signature instead? And of course any tips on where I should look to do this.

**Comment by esengulov** [comment]
> First of all... I was looking at the example and I noticed that the library is making calls to http://btc-testnet.horizontalsystems.xyz/apg. Can somebody tell me why and if it is possible to easily remove these calls? If not at least give me some details on what is returned so we can maybe replace it with our own backend.

Hello, yes it's possible and not hard at all. First, the reason it's being used is for "restore wallet" functionality. In other words, if the user already had a BIP44 compliant wallet there is an option for him to restore access to that wallet instead of creating a new one. That's the reason why app needs access to a third-party explorer to download all transactions relevant to that wallet since day one. In the coming future we are planning to get rid of that dependency and allow user to restore directly from blockchain. Infact, most of the functionality for that already in the library. the only downside is the speed here. restoring from blockchain would take significantly more time. That's why we left it this way for now but plan to allow user to select whether to restore directly from blockchain (private but slow) rather then via a third-party (less private but faster)

**Comment by esengulov** [comment]
> The second one is more complicated. Our client is developing a hardware wallet and for us to successfully implement support for that we need to get access to the low level transaction data that we can then send to the device for signature. My question is - how hard would it be to modify this library so it could be initialized without mnemonics/seed (so in "read only" mode) and modify it to get access to the raw transaction data so that the hardware device can provide the signature instead? And of course any tips on where I should look to do this.

The library we provide can handle all of the requirements you may have provided that such functionality is supported by the underlying blockchain (in this case Bitcoin and Bitcoin Cash). Considering that this library is implemented on Swift and there is one for Android it means that first you hardware wallet needs to have an iOS/andorid app/interafce which would do communication with blockchain but the actual keys can be stored on the hardware wallet which would sign the transactions. I don't think it's a challenging task but obviously you need to digg deeper and what issues you may end up with. I would like to be more specific but at this point we don't have any experience with hardware wallets so not entirely sure about specifics. That said, what you're trying to achieve is already implemented on Android OS version 7 and above where secret keys are handled by a separate section of OS and dedicated hardware https://developer.android.com/training/articles/keystore.

**Comment by r00li** [comment]
Excellent. I am not too concerned with the external backend need for now. Our client would prefer blockchain only option, but our main priority is getting the cold wallet running first.

We have the hardware communication figured out already - cold wallet hardware is working fine with Ethereum/ERC20 tokens, but we are now trying to tackle the Bitcoin part.

What we get from the hardware device is the public key (xpub). The issue that I am having right now is how to modify the library to get the list of transactions/balance (and of course address derivation) while only providing the public key.

**Comment by esengulov** [comment]
Bitcoin SPV client is considered to have master primary key derived from mnemonic/seed or wherever. Or at least, it must have public keys used in all your transactions  This is because SPV client doesn't download the whole blocks. It needs all possible public keys used in transactions to get those transactions.

In this library those public keys are managed and used by 2-3 classes. You only need to customize those classes to get what you need

> Excellent. I am not too concerned with the external backend need for now. Our client would prefer blockchain only option, but our main priority is getting the cold wallet running first.
> 
> We have the hardware communication figured out already - cold wallet hardware is working fine with Ethereum/ERC20 tokens, but we are now trying to tackle the Bitcoin part.
> 
> What we get from the hardware device is the public key (xpub). The issue that I am having right now is how to modify the library to get the list of transactions/balance (and of course address derivation) while only providing the public key.

**Comment by r00li** [comment]
Hmmm, what I am trying to do is this...
Inside `HDWallet.swift` there is a method `publicKey` which the library uses to get the public keys. My idea was to change that method so instead of deriving the key from private key it would derive that key from xpub.

My testnet public key that I get from the device is this:
`tpubDDYDWoUhYtXEFLqrfdL4UeKCBPLMDZBb2Svfi7UeCvEt4pWHiBD2AkvVYCUBsk4uHo9yYMJc1uQjtjaLPTx8RBKuZv844rmnZ9CsAb41fJ4`

So if I am not mistaken I should be able to change that method so it would look like this - for this specific key of course:
```
        var key = HDPublicKey(
            raw: Data(bytes: [0x03, 0x59, 0x5d, 0x88, 0x0c, 0xfe, 0xb1, 0x11, 0xc4, 0xd8, 0x46, 0x83, 0xc7, 0xd7, 0x2e, 0x69, 0x2a, 0x6f, 0x58, 0x3c, 0xcf, 0x24, 0xc4, 0x11, 0x96, 0x40, 0x77, 0x47, 0x27, 0x20, 0x12, 0xa8, 0xd7]),
            chainCode: Data(bytes: [0x22, 0x41, 0x9c, 0x4e, 0xf5, 0x63, 0x42, 0x02, 0x92, 0x16, 0x51, 0xe2, 0x59, 0xc4, 0xab, 0xf8, 0x93, 0x0e, 0x32, 0x0e, 0x6d, 0x3d, 0xa7, 0xf5, 0x29, 0x98, 0xca, 0x09, 0x25, 0xdd, 0x4e, 0x2b]),
            xPubKey: 0x043587cf,
            depth: 0x03,
            fingerprint: 0xcdfed67d,
            childIndex: 0x80000000)
        return key.derived(at: index)
```
This obviously doesn't work correctly. But I am not exactly sure why. Basically running the sync with the method modified like this will give me balance 0. So something with this is wrong - either I don't understand how key derivation works or there is something else.

**Comment by esen** [comment]
Hey @r00li ,

Please could you check if you are getting correct addresses from generated public keys from xpub. Just check `addressConverter.convert(keyHash: publicKey.keyHash, type: .p2pkh).stringValue`.

Also, you would be syncing infinitely the way you are changing that method. Because, you're ignoring `account` parameter. It generates publicKeys for each account (starting from 0, 1, ...) until it has `gapLimit` number of unused publicKeys for an account. It will be getting the same publicKeys for any account, so it will be generating again and again if there's any transaction found. In order to disable that behavior, remove iteration over accounts in `InitialSyncer` and `AddressManager`

**Comment by r00li** [comment]
Thanks for the tips. The addresses that I was getting were wrong - I needed another derivation step for the account.
Returning...
```return key.derived(at: account).derived(at: index)```
started giving me valid addresses. And the sync started working as well... well sort off.

It gets the correct balance and transaction list. But realm crashes at the end of sync (when it reaches 100%) for some reason...
```Terminating app due to uncaught exception 'RLMException', reason: 'Attempting to create an object of type 'Block' with an existing primary key value '000000000000003e0d0f4782df67ca1d46472c7913470621377bcb2424833efe'.'```

**Comment by esen** [comment]
We've removed Realm in master branch. It gets too complicated when used in concurrent threads. This error is one of them. We've just switched to GRDB. Please, check the master branch. It's not stable right now. We're also working on big restructuring of this kit, so it may be unstable for some time before next release.

**Comment by esengulov** [comment]
> Do you by any chance have a rough timeframe for the next stable release? I don't want to make too much changes right now and then have them break when the library is updated. Also... many thanks for the library! This is the only up to date Bitcoin SPV library for iOS that comes near to what we actually need.

Thank you for the feedback !

We expect to have next stable release within next 2-4 weeks. It's ready for the most part and being refactored at this point before pushed to production. It's one of our core tasks at the moment and therefore it's unlikely to delay significantly as we can't move forward with other items on agenda before it's done. I would recommend waiting for the release before applying too many changes)

**Comment by r00li** [comment]
So during this time I was exploring the transaction signing process and I have a question that maybe somebody can help me with...

The hardware device that we are developing for is using the Trezor protocol for transaction signing process:
https://wiki.trezor.io/Developers_guide:Message_Workflows
Basically you initiate the transaction signing process then the device asks you for the details about the transaction... so the inputs, outputs, key derivation path, ...

The device is failing the transaction signing process with the error "Encountered invalid prev_hash". Now the prev_hash value gets set when the device requests information about the previous inputs. In addition the prev_index and script_sig are also set in that step. The prev_hash values that I set are all valid hashes (can be seen on blockchain) so I am starting to get suspicious of the script_sig field that we are setting. 

So to the question... Currently we are setting the value found in the signatureScript of the Input object from this library. And this looks too long to me - around 100 bytes. But the guys over at the android team (that are using BitcoinJ) produce a signature that is 35 bytes long. We are both using the same account. So my question - what is contained in the signatureScript field on the Input object? So is that the actual raw signature script data or is it something else?

**Comment by esen** [comment]
@r00li , the input's script_sig field used for signing is not the value set in `signatureScript` field. When signing it uses the locking script of the previous output OR empty data if it's the same input which is being signed. See [here](https://github.com/horizontalsystems/bitcoin-kit-ios/blob/f30c983d406d2b361d0fcbe4c83c9ddc9df9f2b1/BitcoinCore/BitcoinCore/Serializers/TransactionInputSerializer.swift#L36)
