### ISSUE TITLE
podspec out of date

### ISSUE THREAD

**Issue by tanstaafl856** [horizontalsystems/bitcoin-kit-ios#370]
HSBitcoinKit.podspec.json defines v0.4.1. current version is 0.5?

**Comment by tanstaafl856** [comment]
https://github.com/CocoaPods/Specs/blob/master/Specs/2/3/8/HSBitcoinKit/0.4.1/HSBitcoinKit.podspec.json

**Comment by esen** [comment]
We have renamed the pod to 'BitcoinKit.swift'.

[Cocapods page](https://cocoapods.org/pods/BitcoinKit.swift)
[Spec](https://github.com/CocoaPods/Specs/blob/master/Specs/c/3/b/BitcoinKit.swift/0.5.1/BitcoinKit.swift.podspec.json)
