### ISSUE TITLE
Converting addresses 

### ISSUE THREAD

**Issue by tanstaafl856** [horizontalsystems/bitcoin-kit-ios#376]
In version 0.4.1 print(bitcoinKit.debugInfo) output 3 addresses for each path index; a [BIP32? 84?] bech32, a [BIP44] legacy, and a [BIP49? 141?] SH(WPKH). In v0.5.1 only the bech32. 

Is there a clean way that I am missing to perform the conversion at the BitcoinKit.swift level? Or plans to implement such a conversion? So far everything I have tried at the DataProvider.debugInfo level either does nothing [always prints bech32 regardless of address type indicated] or throws a runtime error.

How about a way to pull an address at a specific derivation path [ex. m/44'/0'/0'/0/17']?

**Comment by ant013** [comment]
We use debugInfo just for currently needed information in debug. So we print only segwit address.
After implement addressConverterChain for separate converters, BitcoinKit uses segwitConverter and legacy, BitcoinCashKit - CashBech32Converter, Dash - only legacy.

You can get all types of addresses in BitcoinKit.swift level using new addressConverterChain from BitcoinCore. Or you have to  implement method in BitcoinKit to get address from BitcoinCore:
- addressConverter.convert(keyHash: Data(hex:"93ce48570b55c42c2af816aeaba06cfee1224fae")!, type: .p2pkh) return legacy address for keyHash
- addressConverter.convert(keyHash: Data(hex:"001493ce48570b55c42c2af816aeaba06cfee1224fae")!, type: .p2wpkh) return segwit address for keyHash with 0014 push codes
- addressConverter.convert(keyHash: Data(hex:"93ce48570b55c42c2af816aeaba06cfee1224fae")!, type: .p2wpkhSh) return witnessPublicKeyHash in scriptHash if keyHash is scriptHash of 0014[publicKeyHash]

You can’t pull an address at a specific derivation path using existing class architecture. You can use HSHDWalletKit
pod from our repository directly and create PublicKey class to make publicKey
