### ISSUE TITLE
macOS support

### ISSUE THREAD

**Issue by cuhte3** [horizontalsystems/bitcoin-kit-ios#462]
Great library! I am wondering if you have plans for supporting macOS? 

Thanks

**Comment by esengulov** [comment]
> Great library! I am wondering if you have plans for supporting macOS?
> 
> Thanks

hi there, glad you found our library useful!

We have considered releasing desktop version not so long ago and decided to postpone it for the time being. At this point we don't have any concrete timeline for it ... At this point we are a bit stretched and our core focus in the near future is lighting network.
