### ISSUE TITLE
How to locally signing in.

### ISSUE THREAD

**Issue by rachkumar** [horizontalsystems/bitcoin-kit-ios#507]
Hi please help me to locally signing in..Add some sample code here.

**Comment by esen** [comment]
Hi @rachkumar,

What do you mean by "signing in"? Do you mean to restore your wallet using mnemonic words? If yes, than please look at [here](https://github.com/horizontalsystems/bitcoin-kit-ios#usage)

**Comment by rachkumar** [comment]
let words = []
    
        let mnemonic = Mnemonic.seed(mnemonic: words)
        
        do {
            let bitcoinKit = try BitcoinKit(withWords: words, bip: .bip44, walletId: "bitcoin-wallet-id", syncMode: .api, networkType: .testNet)
            
            print("address", bitcoinKit.receiveAddress())
            //bitcoinKit.start()
            bitcoinData = bitcoinKit
            
            let wallet = HDWallet(seed: mnemonic, coinType: .zero, xPrivKey: .init(), xPubKey: .init())
            let path = "m/44'/1'/0'/0"
            let privateKey = try wallet.privateKey(path: path)
            
            let testKey = try wallet.privateKey(account: .zero, index: .zero, chain: .external)
            print("myPrivateKey1", testKey.raw.base64EncodedString())
            
            let publicKey = try bitcoinKit.receivePublicKey()
            print("publicKey", publicKey)
            
            
        } catch (let err) {
            print("err occ", err)
        }
    }

Above is my code..I need to get private key..how to get??

**Comment by esen** [comment]
If you mean private key in hex format, than try 
`testKey.raw.reduce("") { $0 + String(format: "%02x", $1) }`

**Comment by rachkumar** [comment]
There is no value called reduce("").
I just need to get private key as same as https://iancoleman.io/bip39/ provides.

**Comment by esen** [comment]
OK, you mean extended private key.

Well, in this repository that's not possible out of the box. There's a method in [hd-wallet-kit-ios](https://github.com/horizontalsystems/hd-wallet-kit-ios/blob/master/HdWalletKit/Classes/HDPrivateKey.swift#L41) that builds that string for you, but it's not public. So you can either access it within hd-wallet-kit-ios or implement that method yourself somewhere else.
