### ISSUE TITLE
How to get private key in string value

### ISSUE THREAD

**Issue by rachkumar** [horizontalsystems/bitcoin-kit-ios#508]
let mnemonic = Mnemonic.seed(mnemonic: words)
    
    do {
        let bitcoinKit = try BitcoinKit(withWords: words, bip: .bip44, walletId: "bitcoin-wallet-id", syncMode: .api, networkType: .testNet)
        
        print("address", bitcoinKit.receiveAddress())
        //bitcoinKit.start()
        bitcoinData = bitcoinKit
        
        let wallet = HDWallet(seed: mnemonic, coinType: .zero, xPrivKey: .init(), xPubKey: .init())
        let path = "m/44'/1'/0'/0"
        let privateKey = try wallet.privateKey(path: path)
        
        let testKey = try wallet.privateKey(account: .zero, index: .zero, chain: .external)
        print("myPrivateKey1", testKey.raw.base64EncodedString())
        
        let publicKey = try bitcoinKit.receivePublicKey()
        print("publicKey", publicKey)
        
        
    } catch (let err) {
        print("err occ", err)
    }
}

**Comment by esen** [comment]
This issue duplicates #507
