### ISSUE TITLE
how I can just sign bitcoin transaction for sending to server?

### ISSUE THREAD

**Issue by iHarmanVirk** [horizontalsystems/bitcoin-kit-ios#525]
In current library I am able to find send method for sending transaction but unable to find sign transaction method.

**Comment by esen** [comment]
Hey @iHarmanVirk,

[InputSigner.swift](https://github.com/horizontalsystems/bitcoin-kit-ios/blob/master/BitcoinCore/Classes/Transactions/Builder/TransactionSigner.swift) signs the transaction. You need to build a MutableTransaction to sign it. See [TransactionBuilder.swift](https://github.com/horizontalsystems/bitcoin-kit-ios/blob/master/BitcoinCore/Classes/Transactions/Builder/TransactionBuilder.swift)

**Comment by iHarmanVirk** [comment]
Okay @esen I will try it and let you know and also it show some compile time error for bitcoin when i archive project.

**Comment by esen** [comment]
> Okay @esen I will try it and let you know and also it show some compile time error for bitcoin when i archive project.

We have some libraries in C like secp256k, which can't be compiled to bitcode. So you have to disable bitcode in build options for your target.

**Comment by iHarmanVirk** [comment]
> Hey @iHarmanVirk,
> 
> [InputSigner.swift](https://github.com/horizontalsystems/bitcoin-kit-ios/blob/master/BitcoinCore/Classes/Transactions/Builder/TransactionSigner.swift) signs the transaction. You need to build a `MutableTransaction` to sign it. See [TransactionBuilder.swift](https://github.com/horizontalsystems/bitcoin-kit-ios/blob/master/BitcoinCore/Classes/Transactions/Builder/TransactionBuilder.swift)

@esen Not able to access TransactionBuilder and TransactionSigner because both were define as internal/private

Please define it public or create new method for just signing in BitcoinCore library

**Comment by esen** [comment]
> @esen Not able to access TransactionBuilder and TransactionSigner because both were define as internal/private
> 
> Please define it public or create new method for just signing in BitcoinCore library

It's OK for us to create a new method for just signing. But this method will require a `MutableTransaction` object ready. That is, `Transaction`, list of `InputToSign` objects including `Input`(with `signatureScripts`, `witnessData`, etc) `PublicKey`, previous `Output`, list of `Output` objects including `lockingScriptData`, etc. I mean, that if you have just a raw unsigned transaction it's way hard to convert it to `MutableTransaction` object that method requires. 

What is use case? Could you explain your needs.

**Comment by iharmandeep** [comment]
@esen 

I am working on app where it provide services for currency support like Ethereum, ERC20 token, and Bitcoin.

Ethereum, and ERC20 token is working fine.

**flow for send money to another customer.**

> firstly user have to create new HD account or recover HD account.
> then user can send money by signing transaction from his private key from his device.
> then I send signed transaction to our own server and server will keep track for user transactions. ( basically that is why I need signed transaction )
 
**what I need?**

> I need a sign bitcoin transaction for send to server.

**what I did in past few days**

> I forked your library and change code for myself for signing transaction and basically I don't Its working or not. because I am unable to get balance for bitcoin. ( why I changed code by myself? because when I am installed pods for same, it install version 0.11.0 because of my other dependencies( eg:- web3, cryptoSwift ) ) 

**Another issue?**

> I am unable to get balance, it always give me zero balance.

**One more questions**

How long it takes to sync account when using syncMode as .api

**Comment by esen** [comment]
> then I send signed transaction to our own server and server will keep track for user transactions. ( basically that is why I need signed transaction )

So you don't need to build that transaction yourself, right? You only need the kit not send the transaction. You need a signed raw transaction ready for sending, which you could send to your own server for sending/tracking? If so, I think, we can create a ticket and make it possible to just build a transaction without sending to peers.

> I forked your library and change code for myself for signing transaction and basically I don't Its working or not. because I am unable to get balance for bitcoin. ( why I changed code by myself? because when I am installed pods for same, it install version 0.11.0 because of my other dependencies( eg:- web3, cryptoSwift ) )

Unfortunately, we don't support any older versions of this kit. The last version is stable and we're using it in our app in production.

> I am unable to get balance, it always give me zero balance.

Please, make sure you are setting right BIP, and make sure that kit is fully synced with blockchain

> How long it takes to sync account when using syncMode as .api

The sync time may vary from 15 - 60 minutes. It depends on the last checkpoints update.

**Comment by iharmandeep** [comment]
> So you don't need to build that transaction yourself, right? You only need the kit not send the transaction. You need a signed raw transaction ready for sending, which you could send to your own server for sending/tracking? If so, I think, we can create a ticket and make it possible to just build a transaction without sending to peers.

Yes right. I can try but before that I have to tell you that I worked on block chain from last 2 month only, so I don't think I have enough knowledge to help you for new ticket. but It will be very helpful if you can at your side.

another questions?

> The sync time may vary from 15 - 60 minutes. It depends on the last checkpoints update.

Do we still have to sync if we just want to sign the new transaction?

> Please, make sure you are setting right BIP, and make sure that kit is fully synced with blockchain

Actually I think problem is kit is not fully synced that why it give me zero balance. but I need to sign transaction immediately, I don't think any user will wait for 15 - 60 minutes. so let me know is it possible to immediately sign functionality?

> Unfortunately, we don't support any older versions of this kit. The last version is stable and we're using it in our app in production.

can you let me know how I can install latest version of this library because it show me version error for other libraries like which are depended on other( eg:- like bitcoin-kit-ios and web3 both use BigInt library, but different version eg:- bitcoin-kit-ios -> 5.0 and web3 -> 4.0 ), I hope you understand this problem.

**Comment by esen** [comment]
@iharmandeep 

We'll add that method soon then.

> Do we still have to sync if we just want to sign the new transaction?

Yes. This is how Bitcoin blockchain syncing works. It needs all your previous transactions to build a new one. You can't create a transaction without having the actual state of your balance

> can you let me know how I can install latest version of this library because it show me version error for other libraries like which are depended on other( eg:- like bitcoin-kit-ios and web3 both use BigInt library, but different version eg:- bitcoin-kit-ios -> 5.0 and web3 -> 4.0 ), I hope you understand this problem.

You can fork this repository and downgrade BigInt version to what web3 requires, I guess
