### ISSUE TITLE
Checkpoint caculation

### ISSUE THREAD

**Issue by softskillpro** [horizontalsystems/bitcoin-kit-ios#540]
@esen @mNizhurin @ant013 
Hi, Awesome @horizontalsystems team!
I wanna add some altcoins here.
But I wonder how can I define checkpoint files for them.
Could you have a chance to tell me?

**Comment by esengulov** [comment]
> @esen @mNizhurin @ant013
> Hi, Awesome @horizontalsystems team!
> I wanna add some altcoins here.
> But I wonder how can I define checkpoint files for them.
> Could you have a chance to tell me?

Checkpoints are relevant for Bitcoin and alike blockchains, you don't need it for ETH or EOS based tokens.

**Comment by softskillpro** [comment]
@ealymbaev  
Hi. How are you.
I want your help for my altcoin.
My altcoin is based on bitcoin 17.0.1.
