### ISSUE TITLE
BTC: initial syncer fails to sync in TEST NET

### ISSUE THREAD

**Issue by cuhte3** [horizontalsystems/bitcoin-kit-ios#572]
First of all I'd like to thank for your brilliant work on the library! <3

Am having an issue syncing a new wallet in TEST NET. InitialSyncer return an error on single.subscribe:

```
invalidResponse(statusCode: 404, data: Optional({
    error =     {
        message = "Not found.";
    };
}))

18:40:41.173 ❤️ ERROR  apiSync: invalidResponse(statusCode: 404, data: Optional({
    error =     {
        message = "Not found.";
    };
}))
```

Previously created wallets syncing with peers just fine as well as syncing new wallet on MAIN NET.  Currently as a workaround I comment out initial syncer and syncing a new wallet with peers, however syncing takes significant more time. Any advices  how to sync a new wallet in TEST NET?

Am using BitcoinCore and BitcoinKit ver 0.17. The issue started no more than couple of weeks ago, previously initial syncer worked without issues.

Thanks!

**Comment by nk-the-crazy** [comment]
Issue resolved by downgrading BCOIN to v1.0.2
