### ISSUE TITLE
BTC test net incorrect balance

### ISSUE THREAD

**Issue by cuhte3** [horizontalsystems/bitcoin-kit-ios#577]
Am using BitcoinKit 0.17 in test net. I've sent 0.00083 tBTC to my wallet (https://blockstream.info/testnet/tx/b95235c6c2224f987f2cbb40cf04ba934ba4b2eac3ef42a890f8e2a3c4ca4087). After receiving the tx balance was correct, my receive address changed, but after 3 days all of a sudden my receive address reverted to a previously used for the incoming tx and frameworks shows a wrong balance of the wallet (0). Also TransactionRecord of the incoming tx doesn't recognise the tx output as mine anymore (output.mine is false). BitcoinKit syncing with peers without any noticeable issues. Is there a way to reset kit state, so it's recognise the tx output as mine and got the correct balance? Any suggestions are welcome.

**Comment by esen** [comment]
Hey @cuhte3, 

Thank you for the report. This looks like a bug to me. Have you tried to delete the app and restore it again? If you have and the problem remains, it's a good news for us. Otherwise, we'll need more information.

**Comment by cuhte3** [comment]
After restoring wallet the issue is reproducible
