### ISSUE TITLE
Cannot send Bitcoin in TestNet

### ISSUE THREAD

**Issue by alexj70** [horizontalsystems/bitcoin-kit-ios#582]
Hi

I cannot send Bitcoin in TestNet

let transaction = try kit.send(to: wallet, value: 1000, feeRate: 70, sortType: .none)
I receive BitcoinCoreErrors.SendValueErrors.singleNoChangeOutputNotFound

the balance: 0.0005 BTC

BitcoinKit: 0.15.4
Xcode Version: 13.2
Swift Version: 13.0

**Comment by esen** [comment]
This exception may be thrown if no appropriate UTXO is found. This may be because of the sum of UTXO values being less than required or the suitable UTXO being spent already (failed to spend).

**Comment by alexj70** [comment]
Thanks
