### ISSUE TITLE
M1 arm64 errors and more

### ISSUE THREAD

**Issue by 13adahan** [horizontalsystems/bitcoin-kit-ios#595]
Hi. Thank you for your work, this is a great project and it will be more than useful if I can implement this to my project.  i am having a lot of stupid errors while trying to start the project. I am currently on M1 Pro chip, with Xcode 13.3. I keep getting a lot of errors. And when I fix those, new ones appear. I got other types of errors on an other git NFT Eth project too, I think it has to do something about my MacBook 2021 16inch. I am leaving an image of one of the many errors I get. And I do not use the simulator, I am aware of the arm64 thing.
<img width="1624" alt="Screenshot 2022-03-28 at 01 34 20" src="https://user-images.githubusercontent.com/65917714/160314788-a9e4c93c-e0aa-459e-b59c-f655a578a88f.png">
if you have in hand a Mac with m1 chip can you verify that there are no problems with the project and you can download the zip, pod install, and start the app? thank you.

**Comment by ealymbaev** [comment]
@13adahan 

We have reproduced your issue and resolved it in #597.

Please try pulling the latest `master` branch

**Comment by 13adahan** [comment]
I really appreciate your time. thank you. it all works perfectly now. I have an older app that is build over the Example folder, that was giving me the same error that I put in the screenshots. Is there any way I can update that without restarting from zero on the new updated example project?
